.vscode/settings.json
components/DetailScreen/DetailHeader.js
components/FeedScreen/Campaign.js
components/Profile/ProfileHeader.js
navigation/AppNavigator.js
navigation/MainTabNavigator.js
screens/CreateCampScreen.js
screens/DetailScreen.js
screens/FeedScreen.js
screens/FormScreen.js
screens/MyDetailScreen.js
screens/MyProScreen.js
screens/ProScreen.js

Changed headers to match design files. Donate links connect to an external website in the in-app browser. Campaign and detail buttons match design file. 

Design updates donate links

---

components/DetailScreen/DetailHeader.js
navigation/AppNavigator.js
package-lock.json
package.json

Open social media links inside of the app using a in app browser, Also for phone it opens a call prompt and auto fills the numbers.
- Social media links are working along with phone number prompt.

links open in app browse, phone number opens a call prompt.

---

navigation/MainTabNavigator.js

remove formscreen

---

navigation/AppNavigator.js
navigation/MainTabNavigator.js
screens/LoadingScreen.js
screens/UsernameScreen.js
store/reducers/index.js

Created conditional error messages to inform the user if their username is valid.
Co-Authored-By: lflores12 <lflores12@users.noreply.github.com>
Co-Authored-By: Zach Christy <zchristy44@gmail.com>

Error Handling

---

package-lock.json
screens/EditDetailScreen.js
screens/FeedScreen.js
screens/LoginScreen.js

Moved the logout button from its temporary place to its permanent location in the edit details screen and styled to UX design

Logout button

---

App.js
components/DetailScreen/DetailHeader.js
screens/CreateCampScreen.js
screens/EditDetailScreen.js
store/actions/index.js

Co-authored-by: Matt Klein <mklein246@gmail.com>
Co-authored-by: Taslim Yakub <taslimer@gmail.com>
Bug fixes for editing profile and details data

bug fixes for editing profile and details data

---

App.js
components/DetailScreen/DetailAboutUs.js
components/DetailScreen/DetailHeader.js
components/FeedScreen/Campaign.js
package-lock.json
screens/CreateCampScreen.js
screens/EditDetailScreen.js
store/actions/index.js

These are bug fixed with the link and issues with editing and linking and also some styling bugs which have been resolved on our end. 

Bug fixes 8/8/2019

---

components/FeedScreen/Campaign.js
constants/Stylesheet.js

fixed spacing between username and campaign description on main feed by adding forced spaces

fixed spacing between username and campaign description on main feed

---

navigation/AppNavigator.js
package-lock.json
package.json
screens/UploadPhoto.js

Photo upload shell built

---

components/FeedScreen/FeedCampaign.js
screens/ProScreen.js

Co-authored-by: Matt Klein <mklein246@gmail.com>

added comments for sticky header

---

components/Profile/SupProfileHeader.js
navigation/MainNavigation.js
screens/ProScreen.js

Co-authored-by: Matt Klein <mklein246@gmail.com>
Fixes for single view merge issues

single view bug fixes

---

screens/EditCampScreen.js
screens/EditProScreen.js
screens/MyProScreen.js
screens/ViewCampScreen.js
store/actions/index.js
store/reducers/index.js

Co-authored-by: Matt Klein <mklein246@gmail.com>
Update to edit campaign screen which now functions as it should.

edit campaign view fixed and single campaign view image sizing changed

---

screens/SearchScreen.js
store/actions/index.js

Search style fix

---

App.js
app.json
components/FeedScreen/FeedCampaign.js
screens/SearchScreen.js
screens/UsernameScreen.js
store/actions/index.js

fixed cross platform issue for multiple iOS devices
Co-Authored-By: Taslim Yakub <taslimy@users.noreply.github.com>

Updated SearchScreen.js

---

App.js
components/DetailScreen/DetailHeader.js
components/Profile/ProfileHeader.js
components/Profile/SupProfileHeader.js
components/withAmplitude.js
constants/DetailScreen/DetailHeader.js
constants/Profile/ProfileHeader.js
constants/screens/EditProScreen.js
constants/screens/EditSupProScreen.js
constants/screens/MyDetailScreen.js
navigation/AppNavigator.js
navigation/MainNavigation.js
package-lock.json
screens/CreateCampScreen.js
screens/CreateCampUpdateScreen.js
screens/DetailScreen.js
screens/EditProScreen.js
screens/EditSupProScreen.js
screens/FeedScreen.js
screens/LoadingScreen.js
screens/LoginScreen.js
screens/MyDetailScreen.js
screens/ProScreen.js
screens/SearchScreen.js
screens/UsernameScreen.js
screens/ViewCampScreen.js
screens/ViewCampUpdateScreen.js
store/actions/index.js
store/reducers/index.js

Tweaking amplitude

---

store/actions/index.js

Added a variable containing the url for axios calls. 

Modified axios calls to use a const url

---

store/actions/index.js

Updating development code to reflect staging heroku db link

---

.expo/packager-info.json
components/Comments/CommentsView.js

Changed regex to trim(). Works the way I want it to. Regex faked me out. 

Comments system

---

constants/Comments/Comments.js
constants/screens/ViewCampScreen.js

💄Style updates: padding for comments in campaign view

---

.expo/packager-info.json
.expo/settings.json
components/Comments/CommentsView.js
constants/Comments/Comments.js

Styling wasn't up to date on development for whatever reason. Adjusted it to be consistent with the latest styling on comments-system... despite having merged comments-system. Quirks of git, I guess! This branch is a clone of development plus styling changes only. 

:lipstick: Adjusted comments styling

---

components/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedCampaign.js
screens/ViewCampScreen.js

Sam asked me to add padding to demarcation in FeedCampaign constant and the comments_length to comments.length is workin'! 

Converted comments_length in FeedCampaign to comments.length

---

.expo/packager-info.json
.expo/settings.json
constants/screens/ViewCampScreen.js
screens/ViewCampScreen.js

Center the donation button for donations. Fixed styling with bottom text thanking users for donations

Center the donation button for android.

---

.expo/packager-info.json
components/Comments/CommentsView.js
constants/Comments/Comments.js

comment submit button fix

---

.expo/packager-info.json
.expo/settings.json
components/Comments/Comment.js

Those deleted comments **GO AWAY** 

Added a ternary to hide deleted comments until re-render

---

.expo/packager-info.json
constants/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedUpdate.js

The spacing was off between the title and the top of the card, and then the bottom of the title before the image.

fixed spacing between t/b of campaign cards

---

.expo/packager-info.json
components/FeedScreen/FeedUpdate.js
constants/FeedScreen/FeedUpdate.js

The Update cards needed both the top and bottom color buttons to overlay on an image and present a slight opacity.

Update campaign cards with updated opacity on buttons

---

.expo/packager-info.json
components/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedUpdate.js

Campaign cards for original posts need some opacity on the See Post bar to match the Update posts, etc.

Campaign cards with See Post bar opacity

---

.expo/packager-info.json
.expo/settings.json
components/FeedScreen/FeedCampaign.js
components/FeedScreen/FeedUpdate.js

This removes the unnecessary bottom color bar that says "See Post" for both original and updated posts. 

Remove "See Post" bar

---

.expo/packager-info.json
components/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedCampaign.js
constants/screens/ViewCampScreen.js
screens/ProScreen.js
screens/ViewCampScreen.js
screens/ViewCampUpdateScreen.js

Bookmarking integrated. Changed colors of likes (and bookmarks). 

Bookmark feature

---

.expo/settings.json
components/UploadMedia.js
constants/FeedScreen/FeedUpdate.js
package-lock.json
package.json

Co-authored-by: Mary Sabol <natsukajiwaram@gmail.com>
Added the ability to upload and preview video for android and iOS. 
- [✔️ ] I have performed a self-review of my own code

:sparkles: Video uploading and video previewing

---

.expo/packager-info.json
.expo/settings.json
screens/ViewCampScreen.js

fixed ios alignment issue

---

.expo/packager-info.json
components/FeedScreen/FeedCampaign.js
constants/DetailScreen/DetailHeader.js
constants/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedUpdate.js
constants/screens/CreateCampScreen.js
screens/CreateCampScreen.js

Updated urgency colors to match the new ones as specified by UX. Slight style changes to create campaign screen. 

Urgency colors + create campaign styling

---

.expo/packager-info.json
components/Comments/CommentsView.js
components/FeedScreen/FeedCampaign.js
constants/Profile/ProfileHeader.js
constants/screens/CreateCampScreen.js
package-lock.json

Fixed alignItems issue with Android, keyExtractor error, and UI Manager warning. 

(3) Bug fixes 10-16

---

.expo/packager-info.json
.expo/settings.json
constants/FeedScreen/FeedCampaign.js
package-lock.json

fixed bookmark color on feed campaign

---

components/FeedScreen/FeedCampaign.js
components/FeedScreen/FeedUpdate.js

Fixed bug that caused expo to crash on Android when using navigationEvents. 
- [✔️  ] I have commented my code, particularly in hard-to-understand areas

:bug: Added HOC to access isFocused prop

---

screens/ProScreen.js

Allows videos to play in ProScreen.

:bug: Added Viewport.Tracker to ProScreen

---

README.md

This is an example of pushing changes.

this is a test 

---

README.md

Fixing test example from last night and updating readme

Fixing test example from last night

---

.expo/packager-info.json
.expo/settings.json
constants/screens/EditProScreen.js
package-lock.json
package.json
screens/EditProScreen.js

removed account settings text and added logout button

---

screens/LoadingScreen.js
store/actions/index.js

typos and console logs removed

---

screens/LoginScreen.js

No more obnoxious token console.logs. Yay.

no more extraneous token and login console.logs

---

navigation/AppNavigator.js
navigation/MainNavigation.js
screens/LogoutScreen.js

Behold. Your logout screen.

---

screens/LogoutScreen.js

fixed the typo

---

.expo/packager-info.json
.expo/settings.json
screens/AccountSettingsScreen.js
screens/EditProScreen.js

The Logout button that Iris designed is now deleted from the Edit Profile screen and is moved to the separate Account Settings page.

Account settings

---

screens/LogoutScreen.js

Components for new onboarding process

User onboarding part two

---

.expo/packager-info.json
.expo/settings.json
screens/AccountSettingsScreen.js

added logout for conservation user

---

screens/org-onboarding-screens/CanScreen.js
screens/org-onboarding-screens/HeyThereScreen.js
screens/org-onboarding-screens/KeyConservationScreen.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js
screens/org-onboarding-screens/ToExpectScreen.js
screens/org-onboarding-screens/VerifyDocumentationScreen.js

Most components for onboarding built out

---

constants/screens/org-onboarding-styles/OnboardingStyles.js

Added some styling that can be (hopefully) used across the Onboarding stack.

:art: Styling for Onboarding

---

components/Airtable.js
package-lock.json
package.json

Endpoint built out. Form with hardcoded sample data will submit new form to Airtable.
State management and dynamic strings are needed. 
Multiple choice fields needed. 
Attachment picker needed.
See docs for API: https://airtable.com/appbPeeXUSNCQWwnQ/api/docs#javascript/table:table%201:list

Airtable form submission working

---

screens/CreateCampScreen.js
screens/EditCampScreen.js
screens/EditProScreen.js
screens/EditSupProScreen.js

Removed Warning: Failed prop type: Invalid prop keyboardType and updated it with phone adnostic 'default' and 'email-address' remained the same.

:bug: updated keyboardType

---

navigation/AppNavigator.js
navigation/MainNavigation.js
screens/org-onboarding-screens/CanScreen.js
screens/org-onboarding-screens/CantScreen.js
screens/org-onboarding-screens/FileOrderDocumentation.md
screens/org-onboarding-screens/HeyThereScreen.js
screens/org-onboarding-screens/KeyConservationScreen.js
screens/org-onboarding-screens/MakeAccountScreen.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js
screens/org-onboarding-screens/ToExpectScreen.js
screens/org-onboarding-screens/VerifyDocumentationScreen.js
screens/org-onboarding-screens/VerifyOrganizationScreen.js

Navigation routes all set up

---

screens/AccountSettingsScreen.js
screens/EditSupProScreen.js
screens/UsernameScreen.js

Logout fixes

---

.expo/packager-info.json
.expo/settings.json
constants/screens/AccountSettingsScreen.js
screens/AccountSettingsScreen.js

Updated styling to match overall profile look.

QA updates - Account Settings styling

---

.expo/packager-info.json
.expo/settings.json
navigation/MainNavigation.js
package-lock.json
package.json
screens/AccountSettingsScreen.js
screens/EditProScreen.js
screens/EditSupProScreen.js
screens/MySupProScreen.js

logout functionality restored

---

screens/LoadingScreen.js
screens/UsernameScreen.js
screens/org-onboarding-screens/HeyThereScreen.js

Specific routing for roles and onboarding

---

.expo/packager-info.json
screens/org-onboarding-screens/HeyThereScreen.js

All logout functionality should now be working.

logout button in 1st new onboarding component now works

---

components/SettingsButton.js

:bug: Click profile crash Android Bug

---

.expo/packager-info.json
.expo/packager-info.json.1065503039
constants/screens/org-onboarding-styles/MakeAccount.js
constants/screens/org-onboarding-styles/TellAboutOrg.js
screens/org-onboarding-screens/MakeAccountScreen.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js

TextInput + KeyboardAvoidingView fixes

---

components/FeedScreen/FeedCampaign.js
components/Sharing/ShareButton.js
components/Sharing/SharingDialog.js

Add campaign info to twitter and facebook post

:construction: Social sharing - twitter and facebook

---

.expo/packager-info.json
package-lock.json
package.json

removed rndebugger, QA check on other bugs

:bug: removed rndebugger, QA check on other bugs

---

screens/org-onboarding-screens/VerifyOrganizationScreen.js

toggle buttons with state

---

components/FeedScreen/FeedUpdate.js
components/Sharing/ShareButton.js
components/Sharing/SharingDialog.js
constants/FeedScreen/FeedUpdate.js

Add share button to FeedUpdate screen, disable linkedIn and Instgaram buttons
- [  X ] I have performed a self-review of my own code

:lipstick: Social share button

---

.expo/packager-info.json
.expo/settings.json
screens/AccountSettingsScreen.js
screens/UsernameScreen.js
screens/org-onboarding-screens/HeyThereScreen.js

In app browser onboarding

---

constants/screens/AccountSettingsScreen.js
screens/AccountSettingsScreen.js
screens/LoginScreen.js

Logout button fixed again, splash screen styling begun.

Logout button, Splash screen

---

screens/LoginScreen.js

Basic login splash screen done.

login screen done sans underline

---

constants/screens/org-onboarding-styles/CanScreen.js
constants/screens/org-onboarding-styles/CantScreen.js
constants/screens/org-onboarding-styles/KeyConservation.js
constants/screens/org-onboarding-styles/MakeAccount.js
navigation/MainNavigation.js
package.json
screens/org-onboarding-screens/CanScreen.js
screens/org-onboarding-screens/CantScreen.js
screens/org-onboarding-screens/MakeAccountScreen.js

Finished the "can" and "can't" screens except for background color and highlight

Onboardy updates

---

.expo/packager-info.json
.expo/settings.json
assets/icons/Back button.svg
constants/screens/org-onboarding-styles/MakeAccount.js
constants/screens/org-onboarding-styles/TellAboutOrg.js
constants/screens/org-onboarding-styles/VerifyDocs.js
constants/screens/org-onboarding-styles/VerifyOrg.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js
screens/org-onboarding-screens/VerifyOrganizationScreen.js

styled screens 10-12 - iris

---

constants/screens/org-onboarding-styles/OrganizationSurvey.js
constants/screens/org-onboarding-styles/ReviewYourInfo.js
screens/org-onboarding-screens/OrganizationSurveyScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/formElement/DropDownSelect.js
screens/org-onboarding-screens/hooks/useForm.js

Add OrganizationSurveyScreen and ReviewYourInfoScreen - Part 1
- [ X  ] I have performed a self-review of my own code

:sparkles: OrganizationSurveyScreen and ReviewYourInfoScreen

---

navigation/MainNavigation.js
package.json
screens/org-onboarding-screens/VerifyDocumentationScreen.js

Add back missing file, resolve merge conflict, hookup steps"

:bug: Organization onboarding screen

---

constants/screens/org-onboarding-styles/HeyThere.js
constants/screens/org-onboarding-styles/ToExpect.js
screens/LoginScreen.js
screens/org-onboarding-screens/HeyThereScreen.js
screens/org-onboarding-screens/ToExpectScreen.js

New styling applied to the 'Hey There' and "What to Expect" screens

Hey There and To Expect screens styled

---

.expo/settings.json
constants/screens/org-onboarding-styles/VerifyDocs.js
screens/org-onboarding-screens/HeyThereScreen.js
screens/org-onboarding-screens/OrganizationSurveyScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/VerifyDocumentationScreen.js
screens/org-onboarding-screens/formElement/NavigateButton.js
screens/org-onboarding-screens/hooks/useForm.js

Add a NavigateButton for organization on-boarding screen
- [ x  ] I have performed a self-review of my own code

:lipstick: Move next button to a separate component

---

screens/LoginScreen.js

Hi-resolution fur image added to the login screen.

hi-res fur image

---

navigation/AppNavigator.js
navigation/MainNavigation.js
screens/AccountSettingsScreen.js

You can get back into your profile whatnots without being sent to the wrong screen

Logout derp

---

components/GoBackButton.js
screens/AccountSettingsScreen.js

losing the back-button for the logout screen

---

.expo/packager-info.json
.expo/settings.json
constants/screens/org-onboarding-styles/VerifyDocs.js
navigation/AppNavigator.js
screens/AccountSettingsScreen.js
screens/org-onboarding-screens/ToExpectScreen.js

some code clean-up

---

constants/screens/org-onboarding-styles/OrganizationSurvey.js
constants/screens/org-onboarding-styles/ReviewYourInfo.js
navigation/MainNavigation.js
screens/org-onboarding-screens/FileOrderDocumentation.md
screens/org-onboarding-screens/OrganizationSurveyScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/ToExpectNextCreateProfileScreen.js
screens/org-onboarding-screens/VerifyDocumentationScreen.js

Add the ToExpectNextCreateProfile Screen, rewire the screens, update file order md, add dummy data to review screen

:lipstick: Add the ToExpectNextCreateProfile Screen

---

.expo/packager-info.json
screens/EditProScreen.js
screens/org-onboarding-screens/OrganizationSurveyScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js
screens/org-onboarding-screens/ToExpectScreen.js
screens/org-onboarding-screens/VerifyDocumentationScreen.js
screens/org-onboarding-screens/VerifyOrganizationScreen.js
screens/org-onboarding-screens/hooks/useForm.js

State from new onboarding process needed for backend automatically populates edit profile screen fields.

Airtable 3

---

screens/EditProScreen.js
screens/org-onboarding-screens/OrganizationSurveyScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/ToExpectNextCreateProfileScreen.js
screens/org-onboarding-screens/VerifyOrganizationScreen.js

Small changes around the components, .maps are commented out until code is fixed.

small tweaks, commented out .maps for now

---

store/actions/index.js

"Dispatch is not a function" bug fix

---

screens/LoginScreen.js

Headroom given to the first splash screen, line break added to match spec.

Login splash page styling

---

screens/LoginScreen.js

Gave the headline on the splash screen a bit of space on the left.

splash screen tweaks

---

.expo/packager-info.json
.gitignore 2
components/FeedScreen/FeedCampaign.js
components/FeedScreen/FeedUpdate.js
constants/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedUpdate.js
screens/ViewCampScreen.js
screens/ViewCampUpdateScreen.js

Got rid of "like" functionality

commented out likes

---

constants/screens/org-onboarding-styles/OrganizationSurvey.js
constants/screens/org-onboarding-styles/ReviewYourInfo.js
screens/org-onboarding-screens/OrganizationSurveyScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js

Add edit functionality to ReviewYourInfoScreen, Correct line height issue to OrganizationSurveyScreen

:lipstick: Add Edit functionality to ReviewYourInfoScreen

---

.expo/settings.json
screens/LogoutScreen.js
screens/UsernameScreen.js

logout page style fixes

---

.expo/packager-info.json
constants/screens/UsernameScreen.js
screens/LogoutScreen.js
screens/VettingCheck.js
screens/org-onboarding-screens/OrganizationSurveyScreen.js
screens/org-onboarding-screens/VerifyOrganizationScreen.js

Vetting page styled and updated

Vetting page styled

---

.expo/packager-info.json
.expo/settings.json
screens/LoadingScreen.js
screens/VettingCheck.js
screens/org-onboarding-screens/OrganizationSurveyScreen.js

App now navigates the conservationist correctly based on their vetting status

vetting navigation issues done

---

.expo/packager-info.json
.expo/settings.json
components/FeedScreen/FeedCampaign.js
components/FeedScreen/FeedUpdate.js
components/Sharing/NOTE.md

Remove Share to social button, added a md file with note
- [ X  ] I have performed a self-review of my own code

Remove Share to social button

---

.expo/packager-info.json
.expo/settings.json
navigation/MainNavigation.js
package-lock.json
screens/maps/WideMapScreen.js

navigation set up for map

---

.expo/settings.json
navigation/MainNavigation.js

icon for map navigation

---

package-lock.json
package.json
screens/maps/WideMap.js

airtable get request functional

---

.expo/packager-info.json
.expo/settings.json
package-lock.json
screens/EditProScreen.js
screens/LoadingScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/VerifyDocumentationScreen.js

Document screen now checks for correct email and document before allowing passage.

Airtable review

---

screens/maps/WideMap.js

boiler plate code for coordinates

---

screens/maps/WideMap.js

Map coordinates

---

.expo/packager-info.json
.expo/settings.json
components/FeedScreen/FeedCampaign.js
components/FeedScreen/FeedUpdate.js
screens/ViewCampScreen.js

commented out code regarding both likes and bookmarks, eliminating that entire "view"

---

.expo/packager-info.json
screens/AccountSettingsScreen.js
screens/LoadingScreen.js
screens/LoginScreen.js
screens/VettingCheck.js
screens/org-onboarding-screens/HeyThereScreen.js
screens/org-onboarding-screens/OrganizationSurveyScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js
screens/org-onboarding-screens/ToExpectNextCreateProfileScreen.js
screens/org-onboarding-screens/VerifyDocumentationScreen.js
screens/org-onboarding-screens/VerifyOrganizationScreen.js

App runs .get request upon login and retrieves airtable API key. Key is saved to SecureStore and distributed throughout onboarding process. LoadingScreen checks if key already exists before executing .get request again.

Env variables

---

.expo/packager-info.json
screens/maps/WideMap.js

pinpoints and functional component

---

screens/maps/WideMap.js

Add map api call api/maps

---

.expo/packager-info.json
.expo/settings.json
screens/AccountSettingsScreen.js
screens/EditProScreen.js
screens/LoadingScreen.js
screens/UsernameScreen.js
screens/VettingCheck.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js
screens/org-onboarding-screens/VerifyDocumentationScreen.js

Fixed some bugs. See commit
- [] I have added tests that prove my fix is effective or that my feature works AND the tests pass

Release 1 bugs

---

store/actions/index.js
store/reducers/index.js

Add react-redux for api/maps call

Add react-redux for api/maps call

---

screens/maps/WideMap.js
store/actions/index.js
store/reducers/index.js

Not working as intended. Base for people to continue working off of. 

added redux

---

.expo/packager-info.json
screens/EditProScreen.js
screens/maps/WideMap.js
store/actions/index.js

Markers how up based on coordinates from backend.

got markers to render based off coords saved in backend

---

components/MapButton.js
screens/maps/WideMap.js
screens/maps/WideMapScreen.js

Map Button component added, Callouts show up for Map Pins.

Callouts added to Map, MapButton created

---

components/MapButton.js
screens/maps/WideMap.js

Org names show up on respective map pins.

Org titles on pins

---

.expo/packager-info.json
.expo/settings.json
screens/maps/WideMap.js

You can now access an unpopulated pro screen onclick

access pro screen now

---

components/Location/LocationMap.js

The screen centers on the marker when location tab is selected, marker also renders the profile image.

Location tab

---

.expo/packager-info.json
.expo/settings.json
components/Location/LocationMap.js
screens/maps/WideMap.js

Styling finished on map pages; stylesheets added.

styling and code clean-up

---

components/Location/LocationMap.js
screens/maps/WideMap.js

centered pin on location tab render and added some documentation

---

App.js
components/FeedScreen/FeedUpdate.js
constants/DetailScreen/DetailAboutUs.js
constants/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedUpdate.js
constants/Profile/ProfileHeader.js
constants/screens/FeedScreen.js
constants/screens/ViewCampScreen.js

Futura now replaces Open Sans completely.

futura everywhere now

---

constants/LocationScreen/LocationHeader.js
constants/screens/FeedScreen.js
constants/screens/UsernameScreen.js
constants/screens/ViewCampScreen.js
screens/CreateCampScreen.js

Updated Font Styles to match the rest of the app

Font stlyes

---

components/Search/MapSearchComponent.js

Updated placeholder text and hid species and habitats option until legit back-end solution is created

Map search bar

---

.expo/packager-info.json
store/actions/index.js

SOMEONE very naughty left the staging db URL in our actions and did not replace it with the production URL. 
This has been fixed.

:ambulance: fixed seturl in actions

---

.expo/packager-info.json
App.js
components/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedUpdate.js
constants/screens/LoadingScreen.js
constants/screens/ViewCampScreen.js
screens/LoadingScreen.js
screens/LogoutScreen.js
screens/UsernameScreen.js
screens/ViewCampUpdateScreen.js

Small tweaks missed in previous QA.

1-17-QA updates

---

screens/org-onboarding-screens/VerifyDocumentationScreen.js

Verify Documentation lo longer checks for document.

commented out airtable check on verify doc

---

.expo/packager-info.json
components/BackButton.js
constants/Buttons/Back.js
screens/FeedScreen.js
screens/MySupProScreen.js
screens/maps/WideMapScreen.js

Back Button + Header Text Fix

---

navigation/MainNavigation.js

Pushing this fix again because it was overwritten.

transitionConfig fix

---

.expo/packager-info.json
components/Comments/CommentsView.js
components/FeedScreen/FeedCampaign.js
components/FeedScreen/FeedUpdate.js
screens/FeedScreen.js
screens/MyProScreen.js
screens/maps/WideMapScreen.js
store/actions/index.js

The dev branch had the wrong SetURL, fixed to staging. Fixed padding for header title. 

SetURL + Padding fix

---

components/LoadingScreenMov.js

🎨Gets rid of old, unused code

---

components/LoadingScreenMov.js

Added Megan's new version of intro video
- [ x ] I have performed a self-review of my own code
- [ x ] I have removed the expo files from my commit
- [ x ] I have commented my code, particularly in hard-to-understand areas

Loading screen mov

---

assets/jsicons/headerIcons/map-marker.js
assets/jsicons/headerIcons/plusLightening.js
components/Profile/SupProfileHeader.js
constants/Profile/SupProfileHeader.js
screens/MyProScreen.js

Fixes syntax error in icon js file and adds map marker icon to supporter profile header

---

screens/MyProScreen.js
screens/SupProScreen.js

Deletes header titles from profile screens to match stakeholders design

Deletes header titles from profile screens

---

screens/MyProScreen.js
screens/ProScreen.js
screens/SupProScreen.js
store/actions/index.js

This pull request fixes breaking issues caused by last merge

Fix destruction from last merge

---

screens/LoginScreen.js

Fix syntax error in LoginScreen.js

---

app.json

This branch is to find and fix the reason the map view causes the live app to crash on androids. 
-added googleMaps api key in app.json
- [ x ] I have performed a self-review of my own code

added googleMaps api key in app.json

---

components/Comments/CommentsView.js

Fixed comment error when you hit enter on the keyboard

Fixed comment error when you hit enter on the keyboard

---

components/Comments/CommentsView.js
store/reducers/index.js

This fixes the issue of the disappearance of all the comments when you delete one comment. The problem was in the filter method in the reducer for DELETE_COMMENT_SUCCESS

Comment delete error

---

components/Auth/LoginForm.js
components/FeedScreen/FeedCampaign.js
components/FeedScreen/FeedUpdate.js
constants/screens/LoginScreen.js
package.json
screens/LoginScreen.js
screens/ViewCampScreen.js
screens/ViewCampUpdateScreen.js
store/actions/index.js
yarn.lock

- Remove sign in with google button (included explanation in comment as to why and how to implement Google OAuth)
- Improve Keyboard handling
- Adjusted actions and axiosWithAuth to receive correct data and properly handle a deactivated user account
- Fix breaking styling error that prevents a user from getting into the app

Auth Screen Fixes & Improvements

---

components/Comments/Comment.js
components/Reports/ReportDetailCard.js
screens/CreateReportScreen.js

Fix breaking issue where an admin is unable to take action on reports
Fix issue where attempting to report a comment is inaccurate in reporting the right comment
Fix issue where owner of a post/comment can report their own post

Reporting System Fixes & Tweaks

---

screens/LoginScreen.js
screens/UsernameScreen.js
store/actions/index.js

This update adds a missing function call for sign up

Fix missing function call in createUser

---

package.json
test/index.test.ts

I believe the set up is complete
I believe the set up for code climate badge is complete
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation

setting up code climate

---

constants/screens/CreateReportScreen.js
screens/CreateReportScreen.js

- Fix an issue where the picker requires a user to expand twice
- Improve button styling to be more accessible and more continuous with the app's design

CreateReportScreen fixes & improvements

---

components/FeedScreen/FeedCampaign.js
components/Profile/ConnectFurther.js
components/TakeAction/TakeActionCta.js

-  changed text of Take Action button to Donate
- this button conditionally rendered if there is a value for org_cta
- linkedIn and gitHub icons commented out until implemented in backend
- [ x ] I have performed a self-review of my own code

Update supporter profile

---

README.md

github + slack integration test

:zap: test

---

components/BackButton.js
components/Connections/ConnectionsHeader.js
components/Connections/OrganizationsCard.js
components/Connections/PeopleCard.js
components/Connections/SelectedOrgCard.js
components/Connections/SelectedPeopleCard.js
navigation/MainNavigation.js
screens/Connections/SelectedConnectionsScreen.js
screens/Connections/tabs/SelectedOrgScreen.js
screens/Connections/tabs/SelectedPeopleScreen.js

Connect feature fixes and improvements

---

components/Connections/PeopleCard.js

Co-Authored-By: Jasmine Kasheboon Khoury <jasminekh96@gmail.com>

Fixes pending connections render bug

---

store/actions/index.js

Switch URL from local for debug to heroku default

Switch URL back to Heroku

---

screens/EditProScreen.js
screens/org-onboarding-screens/SearchProjectsScreen.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js
screens/org-onboarding-screens/TellMoreScreen2.js

When a new user registers without a profile pic, it defaults to the silhouette.

Make profile pic default to silhouette if none specified

---

components/Connections/ConnectionsHeader.js
components/Connections/OrganizationsCard.js
screens/EditProScreen.js
screens/EditSupProScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js
store/actions/index.js

Fix issue editing name

---

assets/jsicons/detailAboutUs/File.js
components/Profile/ProfileBody.js
components/Profile/ProfileHeader.js
components/Profile/tabs/Details.js
constants/FeedScreen/FeedCampaign.js
constants/Profile/ProfileBody.js
constants/Profile/ProfileHeader.js
constants/Profile/tabs/Details.js
screens/EditProScreen.js

3-2 QA updates

---

components/Connections/PeopleCard.js
components/Connections/SelectedOrgCard.js
components/Connections/SelectedPeopleCard.js
components/Profile/ProfileHeader.js

Connect feature new

---

assets/jsicons/bottomnavigation/Lightening.js
components/UploadMedia.js
constants/UploadMedia.js
constants/screens/CreateCampScreen.js
constants/screens/EditCampScreen.js
constants/screens/EditProScreen.js
constants/screens/EditSupProScreen.js
screens/CreateCampScreen.js
screens/CreateCampUpdateScreen.js
screens/EditCampScreen.js
screens/EditProScreen.js
screens/EditSupProScreen.js

- Update all forms in the app to match designs
- Refactor forms to be more performant
- Refactor upload media button to match designs, and to accept custom style props for reusability

Overhaul forms

---

README.md

Connect feature routing completed

---

components/Onboarding/ChoosePhoneSwitches.js
constants/screens/org-onboarding-styles/VerifyDocs.js
screens/org-onboarding-screens/AccountScreen.js
screens/org-onboarding-screens/MakeAccountScreen.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
screens/org-onboarding-screens/TellMoreScreen.js
screens/org-onboarding-screens/VerifyDocumentationScreen.js
store/actions/index.js

fixed next button bug, changed order of screens as per design files

---

screens/ReportDetailScreen.js
store/actions/index.js
store/reducers/index.js

Fixes an issue where ReportDetailScreen is stuck in a loading state

Fix loading state issue in ReportDetailScreen

---

components/FeedScreen/FeedCampaign.js
components/TakeAction/TakeActionCta.js
constants/FeedScreen/FeedCampaign.js
constants/TakeAction/TakeActionCta.js

Changes color & width to match design and fixes browser bug

---

components/Profile/ConnectFurther.js
components/Profile/tabs/Details.js

ConnectFurther added back to supporter profile
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.

ConnectFurther added back to supporter profile

---

screens/CreateCampScreen.js

Fix loading state issue when creating a campaign with incomplete data

---

components/FeedScreen/FeedCampaign.js
components/TakeAction/TakeActionCta.js
screens/ViewCampScreen.js

donate button renders for all user types
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.

buttons rendering for all user types

---

components/Profile/ProfileBody.js
screens/ProfileScreen.js

Fixes myProfile campaign bug

---

store/actions/index.js

Switch URL to regular production

---

screens/org-onboarding-screens/TellAboutOrganizationScreen.js

Missing import, improper use of custom component fixed

Fix onboarding error not allowing user to begin process

---

store/actions/index.js

Goodbye Seturl u will not be missed 🖕

seturl again

---

screens/VettingCheck.js
screens/org-onboarding-screens/ReviewYourInfoScreen.js
store/actions/index.js

Labs20 hotfix

---

package.json
yarn.lock

installed slack emoji library 

initial commit - slack emoji installation

---

assets/jsicons/KeyCon/LogoutSymbol.js
assets/jsicons/miscIcons/BackArrowHeader.js
constants/Profile/ProfileHeader.js
constants/screens/AccountSettingsScreen.js
constants/screens/EditSupProScreen.js
constants/screens/LoginScreen.js
screens/EditSupProScreen.js

Making tweeks to UI as required in Trello.

UI updates

---

assets/jsicons/KeyCon/LogoutSymbol.js
assets/jsicons/miscIcons/Logout.js
constants/Profile/CampBlankSpace.js
constants/Profile/ProfileHeader.js
constants/screens/AccountSettingsScreen.js
constants/screens/LoginScreen.js
constants/screens/NameScreen.js
screens/LoadingScreen.js
screens/NameScreen.js

QA for 3-23, round two.
- Updated styles in name screen
- Fixed typo in Loading Screen
- Tweaked some padding and margins here and there
- Uploaded screenshots for stakeholder review

QA-3-23 part two

---

navigation/MainNavigation.js
screens/CreateCampaignScreen.js
screens/LoginScreen.js
screens/org-onboarding-screens/TellAboutOrganizationScreen.js
store/actions/index.js

Fix bugs caused by refactor

---

assets/jsicons/CommentIcon.js
components/FeedScreen/FeedCampaign.js

Made comment icon and badge bigger. Change looks good on iPad, but please check on iphone and android before merging.

made comment icon and badge bigger

---

components/FeedScreen/FeedCampaign.js
screens/CreateCampaignUpdateScreen.js
screens/ViewCampaignScreen.js

Fix campaign details/comments screen

---

components/FeedScreen/FeedCampaign.js

The feature to comment on a campaign update hasn't been developed yet, for now just show 0 comments on update cards.

Show 0 comments on campaign updates

---

components/Connections/ConnectionsHeader.js

Fixed connections - the main cause was a backend issue (also fixed in the backend repo), but the error handling was also completely wrong on the frontend, causing empty message boxes to appear. 

Fix connections

---

components/FeedScreen/FeedUpdate.js
constants/FeedScreen/FeedCampaign.js
constants/FeedScreen/FeedUpdate.js
constants/screens/ViewCampaignScreen.js
constants/screens/ViewCampaignUpdateScreen.js
screens/ViewCampaignScreen.js

Small tweaks to get things matching with live feed, viewcampaign, and viewcampaignupdate

Campaign styles

---

screens/ProfileScreen.js

added conditionals for supporters and conservationists

fix supporter profile screen

---

navigation/MainNavigation.js
screens/org-skillimpact-screen/OrgSkillImpactScreen.js
screens/supporter-skillimpact-screen/SupporterSkillImpactScreen.js

- added folders for org and supporters for developing skill tabs on both users types.

divided screens for supporters and orgs

---

components/SkilledImpact/OrgSkilledImpactBody.js
components/SkilledImpact/OrgSkilledImpactHeader.js
constants/SkilledImpact/OrgSkilledImpactBody.js
constants/SkilledImpact/OrgSkilledImpactHeader.js
constants/SkilledImpact/OrgSkilledImpactScreen.js
screens/org-skillimpact-screen/OrgSkillImpactScreen.js
store/actions/index.js

Added the header image and avatar rounded text. <br>
IOS: <br>
<br>
Andriod:

Added Skilled Impact tab header, started with Skilled Impact Tab Body

---

components/Profile/ProfileBody.js

rename org profile header from 'my campaigns' to 'campaigns'

rename org profile header from 'my campaigns' to 'campaigns'

---

components/Auth/AuthForm.js
components/Auth/LoginForm.js
constants/screens/AccountSettingsScreen.js
navigation/MainNavigation.js
screens/AccountSettingsScreen.js
screens/ReportDetailScreen.js

This pull request includes a few bug fixes in miscellaneous areas:
- Fix styling in account settings screen
- Fix broken links in report detail screen
- Fix issue causing login screen to remain in a "Keyboard up" state even after the keyboard has gone down (React Native bug, a successful workaround was implemented)

Bug Fix Package

---

App.js
screens/CreateCampaignUpdateScreen.js
screens/FeedScreen.js
store/actions/index.js
store/reducers/index.js
websockets/WebSocketManager.js

Fix some issues and some final touches

Implement support for updates as well

---

components/CampaignPost.js
components/FeedScreen/NewPostsButton.js
constants/CampaignPost.js
screens/FeedScreen.js
store/actions/index.js
store/reducers/index.js

Fix Android breaking issue

---

App.js
components/CampaignPost.js
components/FeedScreen/AddCampaignHeader.js
components/FeedScreen/UploadQueueCard.js
constants/CampaignPost.js
screens/CreateCampaignScreen.js
screens/CreateCampaignUpdateScreen.js
screens/FeedScreen.js
store/actions/index.js
store/reducers/index.js

This includes a temporary fix for the custom emoji keyboard, as well as improvements and bug fixes and mainly a new upload queue feature that improves user experience when creating posts significantly by no longer interrupting their use of the app and showing a progress bar, allowing the option to cancel, and in a future iteration the ability to retry upon failure.

Overhaul feed

---

store/reducers/index.js

Harden feed data layer

---

App.js
screens/FeedScreen.js
websockets/WebSocketManager.js

Stable build for WebSockets and all feed components

---

websockets/WebSocketManager.js

Further improve stability

---

store/reducers/index.js
websockets/WebSocketManager.js

Further improve WebSockets

---

components/SkilledImpact/elements/SkillContent.js
components/SkilledImpact/elements/SkillsExpand.js
components/SkilledImpact/elements/SupporterCampaignContent.js
constants/SkilledImpact/CampaignContent.js
constants/SkilledImpact/OrgSkilledImpactBody.js
constants/SkilledImpact/SupporterSkilledImpactBody.js

Updated font families and sizes for headers and buttons, and
miscellaneous layout fixes.

Miscellaneous style fixes for skilled impact tabs

---

package-lock.json

Update "httpd-proxy" from 1.18.0 --> 1.18.1 to address a "Denial of Service" vulnerability.
**Trello card: https://trello.com/c/Nacv9ElY/281-critical-security-fix**

Fix high-severity vulnerability

---

__tests__/CampainNotification-test.js
__tests__/__snapshots__/index.test.js.snap
__tests__/index.test.js
babel.config.json
package-lock.json
package.json

I added a test for an action related to notifications. Let's not worry about testing the component rendering for now, there are lots of other functions, like actions, that need testing.
Also, I added a script to enable code coverage for test runs.

An example test and a fix for coverage

---

__tests__/index.test.js

Since you're not returning a Promise, the `then()` won't work. I removed that and the tests now pass.
Note, I ran Prettier on the code and committed it, then committed the fix. There's a `.prettierrc` file in the root, are you all using the Prettier plugin to keep the code formatted?

Fixed tests
